function Hd = equiripple_196
%EQUIRIPPLE_196 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.11 and DSP System Toolbox 9.13.
% Generated on: 09-Jan-2022 02:57:35

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 3840;  % Sampling Frequency

N     = 196;  % Order
Fpass = 90;   % Passband Frequency
Fstop = 105;  % Stopband Frequency
Wpass = 10;   % Passband Weight
Wstop = 1;    % Stopband Weight
dens  = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% [EOF]
